# Whitlock Alacritty Configuration
# Version 2.1

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x405860"
blue = "0x6699cc"
cyan = "0x5fb3b3"
green = "0x99c794"
magenta = "0xc594c5"
red = "0xec5f67"
white = "0xadb5c0"
yellow = "0xfac863"

[colors.normal]
black = "0x29414f"
blue = "0x6699cc"
cyan = "0x5fb3b3"
green = "0x99c794"
magenta = "0xc594c5"
red = "0xec5f67"
white = "0x65737e"
yellow = "0xfac863"

[colors.primary]
background = "0x1b2b34"
foreground = "0xd8dee9"

[env]
TERM = "xterm-256color"

[window]
title = "terminal"
dynamic_title = false
opacity = 0.95
startup_mode = "Windowed"
decorations = "Buttonless"

[window.dimensions]
columns = 120
lines = 32

[window.padding]
x = 10
y = 10

[scrolling]
history = 50000
multiplier = 3
